version: '3.9'
services:
  app:
    image: meselghea/my-backend-extra
    container_name: meselghea-backend-app
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: always